### ISSUE TITLE
how to go get this masterpiece?)

### ISSUE THREAD

**Issue by blank-teer** [dabbertorres/autowire#3]
teach please how to use your fork with autobinding-experiment locally instead of the origin wire?

**Comment by dabbertorres** [comment]
Haven't merged the branch to the main branch yet, nor changed up the `go.mod` and other things to make it work with `go get`, so I would recommend cloning the base repo and applying a patch from my PR for the time being.

**Comment by dabbertorres** [comment]
@blank-teer now a simple `go get` should suffice.

**Comment by blank-teer** [comment]
@dabbertorres 

`go get github.com/dabbertorres/autowire`

produces:

```
go get: github.com/dabbertorres/autowire@none updating to
	github.com/dabbertorres/autowire@v0.5.0: parsing go.mod:
	module declares its path as: github.com/google/wire
	        but was required as: github.com/dabbertorres/autowire
```

heeeelp please I really need get your fork in a civil way instead of brute cloning the repo, etc.

remark:
was doing that after `go clean -modcache` too

**Comment by blank-teer** [comment]
`go get github.com/dabbertorres/autowire/cmd/wire@autobinding-experiment` produces the same

**Comment by dabbertorres** [comment]
`go get github.com/dabbertorres/autowire@main` appears to work for me.

**Comment by blank-teer** [comment]
oh it works, thank! but now i dived into another trouble... how exactly it should work with the following original wire code but using autobinding? 

```
var set = wire.NewSet(
    pubsub.NewQueuer,
    wire.Bind(new(ucrm.WorkQueuer), new(*pubsub.Queuer)),
)
```

**Comment by blank-teer** [comment]
asking because even after replacement `wire` with `autowire` (both executable binary and import sources) it anyway claims that I not provide explicit bindings

**Comment by dabbertorres** [comment]
You will need to declare a provider as eligible for auto-binding.

However this is [not yet merged](https://github.com/dabbertorres/autowire/pull/5), so you can use `go get github.com/dabbertorres/autowire@autobinding` until it is merged.

Here's a working example (I just tried it out):

`main.go`:
```go
package main

type Fooer interface {
	Foo()
}

type Foo struct{}

func (Foo) Foo() {}

func useFooer(f Fooer) {
	f.Foo()
}

func main() {
	f := Run()
	useFooer(f)
}
```

`wire.go`:
```go
//go:build wireinject
// +build wireinject

package main

import "github.com/dabbertorres/autowire"

func Run() Fooer {
	autowire.Build(
		autowire.Struct(new(Foo)),
		autowire.AutoBind(new(Foo)),
	)
	return Fooer(nil)
}
```

Sorry for the delayed response!
